"""Go / Cargo / yarn / pnpm lock-file readers and SemVer range matching (v1.1)."""
from tracegate.lockfiles import ecosystem_for, parse_manifest, pin_lines, semver_key
from tracegate.osv import OsvIndex

YARN_V1 = '''# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/core@^7.0.0", "@babel/core@^7.1.0":
  version "7.1.2"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.1.2.tgz"

lodash@^4.17.0:
  version "4.17.20"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.20.tgz"
'''

YARN_BERRY = '''__metadata:
  version: 6
  cacheKey: 8

"@babel/core@npm:^7.0.0":
  version: 7.22.5
  resolution: "@babel/core@npm:7.22.5"

"app@workspace:.":
  version: 0.0.0-use.local
  resolution: "app@workspace:."

"lodash@npm:^4.17.21":
  version: 4.17.21
'''

PNPM_V5 = '''lockfileVersion: 5.4
importers:
  .:
    specifiers:
      lodash: ^4.17.0
packages:
  /lodash/4.17.21:
    resolution: {integrity: sha512-x}
  /@babel/core/7.1.0_react@18.0.0:
    resolution: {integrity: sha512-y}
'''

PNPM_V9 = '''lockfileVersion: '9.0'
packages:
  '@babel/core@7.24.0':
    resolution: {integrity: sha512-a}
  lodash@4.17.21:
    resolution: {integrity: sha512-b}
snapshots:
  lodash@4.17.21: {}
'''

PNPM_V6 = '''lockfileVersion: '6.0'
packages:
  /@vue/shared@3.3.4:
    resolution: {integrity: sha512-a}
  /vite@4.4.0(@types/node@20.0.0):
    resolution: {integrity: sha512-b}
'''

GO_MOD = '''module github.com/example/app

go 1.21

require github.com/single/dep v0.3.0

require (
\tgithub.com/gin-gonic/gin v1.9.0
\tgolang.org/x/net v0.0.0-20230101000000-abcdefabcdef // indirect
)

replace github.com/gin-gonic/gin => ../gin
'''

GO_SUM = '''github.com/gin-gonic/gin v1.8.0 h1:aaa=
github.com/gin-gonic/gin v1.8.0/go.mod h1:bbb=
github.com/gin-gonic/gin v1.9.0 h1:ccc=
github.com/gin-gonic/gin v1.9.0/go.mod h1:ddd=
golang.org/x/text v0.3.0/go.mod h1:eee=
'''

CARGO = '''version = 3

[[package]]
name = "regex"
version = "1.9.1"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "Serde_Json"
version = "1.0.100"
'''


def test_yarn_v1_and_berry():
    assert parse_manifest("yarn.lock", YARN_V1) == {"@babel/core": "7.1.2", "lodash": "4.17.20"}
    got = pin_lines("web/yarn.lock", YARN_BERRY)
    assert got == {"@babel/core": ("7.22.5", 5), "lodash": ("4.17.21", 13)}  # workspace entry skipped
    assert ecosystem_for("web/yarn.lock") == "npm"


def test_pnpm_v5_v6_v9():
    assert parse_manifest("pnpm-lock.yaml", PNPM_V5) == {"lodash": "4.17.21", "@babel/core": "7.1.0"}
    assert parse_manifest("pnpm-lock.yaml", PNPM_V6) == {"@vue/shared": "3.3.4", "vite": "4.4.0"}
    v9 = pin_lines("pnpm-lock.yaml", PNPM_V9)
    assert v9 == {"@babel/core": ("7.24.0", 2), "lodash": ("4.17.21", 4)}  # snapshots ignored


def test_go_mod_and_sum():
    assert parse_manifest("go.mod", GO_MOD) == {
        "github.com/single/dep": "v0.3.0", "github.com/gin-gonic/gin": "v1.9.0",
        "golang.org/x/net": "v0.0.0-20230101000000-abcdefabcdef"}
    assert pin_lines("go.sum", GO_SUM) == {"github.com/gin-gonic/gin": ("v1.9.0", 2)}  # go.mod-only lines skipped
    assert ecosystem_for("go.sum") == "golang"


def test_cargo_lock():
    assert parse_manifest("Cargo.lock", CARGO) == {"regex": "1.9.1", "serde_json": "1.0.100"}
    assert ecosystem_for("Cargo.lock") == "cargo"


def test_semver_ordering():
    assert semver_key("v1.10.0") > semver_key("1.9.9")
    assert semver_key("1.0.0-beta.2") < semver_key("1.0.0-beta.11") < semver_key("1.0.0")
    assert semver_key("v0.0.0-20230101000000-abc") < semver_key("v0.0.1")


def test_osv_go_and_cargo_ranges():
    recs = [{"id": "GO-2023-0001", "aliases": ["CVE-2023-1"], "summary": "x",
             "affected": [{"package": {"ecosystem": "Go", "name": "github.com/gin-gonic/gin"},
                           "ranges": [{"type": "SEMVER", "events": [{"introduced": "0"}, {"fixed": "1.9.1"}]}]}]},
            {"id": "RUSTSEC-2022-0013", "summary": "y",
             "affected": [{"package": {"ecosystem": "crates.io", "name": "regex"},
                           "ranges": [{"type": "SEMVER", "events": [{"introduced": "0.0.0-0"},
                                                                    {"fixed": "1.5.5"}]}]}]}]
    go = OsvIndex.from_records(recs, "golang")
    assert [v.id for v in go.vulns("github.com/gin-gonic/gin", "v1.9.0")] == ["GO-2023-0001"]
    assert go.vulns("github.com/gin-gonic/gin", "v1.10.0") == []
    cargo = OsvIndex.from_records(recs, "cargo")
    assert [v.id for v in cargo.vulns("regex", "1.5.4")] == ["RUSTSEC-2022-0013"]
    assert cargo.vulns("regex", "1.9.1") == []


def test_mal_semver_ranges_and_prerelease():
    idx = OsvIndex("npm")
    idx.mal["demo-pkg"] = [{"id": "MAL-2099-0001", "versions": [], "ranges": [("1.0.0", "1.0.3", None)]}]
    assert idx.malicious("demo-pkg", "1.0.1")
    assert idx.malicious("demo-pkg", "1.0.2-rc.1.x")
    assert not idx.malicious("demo-pkg", "1.0.3")


def test_long_lines_do_not_backtrack():
    import time
    t = time.perf_counter()
    pin_lines("go.mod", "require (\n" + "a." * 50_000 + "\n)\n")
    pin_lines("requirements.txt", "a" + " " * 100_000 + "x\n")
    assert time.perf_counter() - t < 2


def test_materialize_rejects_traversal_paths():
    from tracegate.gitlineage import safe_relpath
    assert safe_relpath("hc/api/models.py")
    for bad in ("hc/../../marker.py", "/etc/x", "a/.git/config", "c:/x", "a\\b", "./a"):
        assert not safe_relpath(bad), bad
